services:
  directus:
    container_name: directus
    image: directus/directus:11.1.1
    restart: unless-stopped
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    environment:
      SECRET: 'replace-with-secure-random-value'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      WEBSOCKETS_ENABLED: 'true'
    ports:
      - '8055:8055'

  remix:
    container_name: remix
    build:
      context: ./remix
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - '5173:5173'
    environment:
      NODE_ENV: development
      PORT: '5173'
    volumes:
      - ./remix/app:/remixapp/app
      - /remixapp/node_modules
