services:
  directus:
    container_name: directus
    image: directus/directus:11.1.1
    restart: unless-stopped
    env_file: ./directus/.env
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions

  remix:
    container_name: remix
    build:
      context: ./remix
      dockerfile: Dockerfile.prod
    restart: unless-stopped

  caddy:
    container_name: caddy
    image: caddy:2.8-alpine
    restart: unless-stopped
    environment:
      DOMAIN1: localhost:8080
      DOMAIN2: localhost:8443
      DOMAIN3: localhost:8088
    ports:
      - '8080:8080'
      - '8443:8443'
      - '8088:8088'
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./lasstliebeda/index.html:/www/html/index.html
    depends_on:
      - directus
      - remix

volumes:
  caddy_data:
  caddy_config:
